import test from 'node:test';
import assert from 'node:assert/strict';
import { LocalRecords } from '../src/storage.js';
const KEY='3cars.records';
class Memory {constructor(seed={}){this.map=new Map(Object.entries(seed));}getItem(k){if(this.blockRead)throw Error('blocked');return this.map.get(k)??null;}setItem(k,v){if(this.blockWrite)throw Error('quota');this.map.set(k,String(v));}removeItem(k){this.map.delete(k);}}
const entry={carId:'vortex',weather:'dry',position:1,time:310,penalty:0,bestLap:60,finishedAt:'2026-09-21T10:00:00Z'};
test('settings round-trip through a new instance',()=>{const s=new Memory(),r=new LocalRecords(s);assert.equal(r.available,true);assert.deepEqual(r.loadSettings(),{carId:'vortex',weather:'dry',muted:false,quality:'high'});assert.equal(r.saveSettings({carId:'apex',weather:'wet',muted:true,quality:'medium'}),true);assert.deepEqual(new LocalRecords(s).loadSettings(),{carId:'apex',weather:'wet',muted:true,quality:'medium'});});
test('invalid settings, blocked storage, and later read failure are safe',()=>{const s=new Memory(),r=new LocalRecords(s);assert.equal(r.saveSettings({carId:'ghost'}),false);assert.equal(r.saveSettings({unknown:1}),false);s.blockRead=true;r.loadSettings();assert.equal(r.available,false);assert.equal(r.saveSettings({carId:'apex'}),false);const blocked=new Memory();blocked.blockRead=true;assert.equal(new LocalRecords(blocked).available,false);});
test('corrupt and future-version records fall back safely',()=>{for(const value of ['{broken',JSON.stringify({version:2,settings:{carId:'apex'},results:[entry],bests:{'vortex:dry':60}})]){const r=new LocalRecords(new Memory({[KEY]:value}));assert.equal(r.results().length,0);assert.equal(r.bestLap('vortex','dry'),null);assert.equal(r.loadSettings().carId,'vortex');}});
test('quota errors disable persistence without crashing',()=>{const s=new Memory(),r=new LocalRecords(s);s.blockWrite=true;assert.equal(r.saveSettings({muted:true}),false);assert.equal(r.available,false);assert.equal(r.recordRace(entry),false);});
test('all-time best survives history trimming and remains scoped',()=>{const s=new Memory(),r=new LocalRecords(s);r.saveSettings({muted:true});assert.equal(r.recordRace(entry),true);r.recordRace({...entry,weather:'wet',bestLap:75});r.recordRace({...entry,carId:'apex',bestLap:55});for(let i=0;i<25;i++)assert.equal(r.recordRace({...entry,bestLap:80+i,time:500+i}),true);assert.equal(r.results().length,20);assert.equal(r.results()[0].time,524);assert.equal(r.bestLap('vortex','dry'),60);assert.equal(r.bestLap('vortex','wet'),75);assert.equal(r.bestLap('apex','dry'),55);assert.equal(r.bestLap('apex','wet'),null);assert.equal(new LocalRecords(s).bestLap('vortex','dry'),60);assert.equal(r.loadSettings().muted,true);});
test('invalid race data cannot persist',()=>{const r=new LocalRecords(new Memory()),cycle={};cycle.self=cycle;for(const change of [{time:NaN},{time:Infinity},{time:-1},{penalty:-1},{position:4},{carId:'x'},{weather:'snow'},{bestLap:400},{bestLap:0},{finishedAt:cycle},{finishedAt:'bad'},{extra:true}])assert.equal(r.recordRace({...entry,...change}),false);assert.equal(r.recordRace(entry),true);assert.deepEqual(r.results()[0],entry);});
test('blocked localStorage getter is safe',()=>{const original=Object.getOwnPropertyDescriptor(globalThis,'localStorage');Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw Error('blocked');}});try{assert.equal(new LocalRecords().available,false);}finally{if(original)Object.defineProperty(globalThis,'localStorage',original);else delete globalThis.localStorage;}});
